/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 22:19:31 GMT 2022
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Document;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CDataNode_ESTest extends CDataNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("R>\"~bc}l>");
      MockPrintStream mockPrintStream0 = new MockPrintStream("frameset");
      Document document0 = Document.createShell("frameset");
      Document.OutputSettings document_OutputSettings0 = document0.outputSettings();
      cDataNode0.outerHtmlHead(mockPrintStream0, (-1296), document_OutputSettings0);
      assertEquals("#cdata", cDataNode0.nodeName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("R>\"~bc}l>");
      cDataNode0.text();
      assertEquals("#cdata", cDataNode0.nodeName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("R>\"~bc}l>");
      MockPrintStream mockPrintStream0 = new MockPrintStream("frameset");
      Document document0 = Document.createShell("frameset");
      Document.OutputSettings document_OutputSettings0 = document0.outputSettings();
      cDataNode0.outerHtmlTail(mockPrintStream0, (-1296), document_OutputSettings0);
      assertEquals(1, document_OutputSettings0.indentAmount());
  }
}
