/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 22:15:46 GMT 2022
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Comment;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.DocumentType;
import org.jsoup.nodes.Node;
import org.jsoup.nodes.TextNode;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LeafNode_ESTest extends LeafNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DataNode dataNode0 = new DataNode("#cdata", "1BLD)z[9&f1nqw");
      Document document0 = new Document("2vAIi` V");
      dataNode0.parentNode = (Node) document0;
      dataNode0.before("2vAIi` V");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Comment comment0 = new Comment("");
      comment0.baseUri();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Comment comment0 = new Comment("W\"Z_[H AIl:'_E.Q");
      comment0.attr("W\"Z_[H AIl:'_E.Q");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("", "jB.?,+ia(+'", ":%s(%dn)", ":%s(%dn)");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded("Leaf Nodes do not have child nodes.");
      textNode0.doSetBaseUri("");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DataNode dataNode0 = DataNode.createFromEncoded("zb&PtF,FemES.Ic", "method");
      dataNode0.absUrl("method");
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DataNode dataNode0 = DataNode.createFromEncoded("#VR~c!_9|5j", "k!K&]r.Litq,8");
      // Undeclared exception!
      try { 
        dataNode0.ensureChildNodes();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Leaf Nodes do not have child nodes.
         //
         verifyException("org.jsoup.nodes.LeafNode", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("", "", "", "", "");
      documentType0.removeAttr("");
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("M}od%AY3LsZw46/W");
      cDataNode0.toString();
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("M}od%AY3LsZw46/W");
      cDataNode0.text("M}od%AY3LsZw46/W");
  }
}
