/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 22:17:51 GMT 2022
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Iterator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jsoup.helper.W3CDom;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.junit.runner.RunWith;
import org.w3c.dom.DOMException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class W3CDom_ESTest extends W3CDom_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Iterator<Attribute> iterator0 = (Iterator<Attribute>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(iterator0).hasNext();
      Attributes attributes0 = mock(Attributes.class, new ViolatedAssumptionAnswer());
      doReturn(iterator0).when(attributes0).iterator();
      Element element0 = mock(Element.class, new ViolatedAssumptionAnswer());
      doReturn(attributes0).when(element0).attributes();
      doReturn("t+YR:,W?TU{qc\t$x", (String) null).when(element0).tagName();
      Document document0 = mock(Document.class, new ViolatedAssumptionAnswer());
      doReturn("l", "t+YR:,W?TU{qc\t$x").when(document0).location();
      doReturn(element0).when(document0).child(anyInt());
      // Undeclared exception!
      try { 
        w3CDom0.fromJsoup(document0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.helper.W3CDom$W3CBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Iterator<Attribute> iterator0 = (Iterator<Attribute>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(iterator0).hasNext();
      doReturn((Object) null).when(iterator0).next();
      Attributes attributes0 = mock(Attributes.class, new ViolatedAssumptionAnswer());
      doReturn(iterator0).when(attributes0).iterator();
      Element element0 = mock(Element.class, new ViolatedAssumptionAnswer());
      doReturn(attributes0).when(element0).attributes();
      Document document0 = mock(Document.class, new ViolatedAssumptionAnswer());
      doReturn("l", "t+YR:,W?TU{qc\t$x").when(document0).location();
      doReturn(element0).when(document0).child(anyInt());
      // Undeclared exception!
      try { 
        w3CDom0.fromJsoup(document0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.helper.W3CDom$W3CBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Iterator<Attribute> iterator0 = (Iterator<Attribute>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(iterator0).hasNext();
      Attributes attributes0 = mock(Attributes.class, new ViolatedAssumptionAnswer());
      doReturn(iterator0).when(attributes0).iterator();
      Element element0 = mock(Element.class, new ViolatedAssumptionAnswer());
      doReturn(attributes0).when(element0).attributes();
      doReturn("", (String) null).when(element0).tagName();
      Document document0 = mock(Document.class, new ViolatedAssumptionAnswer());
      doReturn("l", "t+YR:,W?TU{qc\t$x").when(document0).location();
      doReturn(element0).when(document0).child(anyInt());
      // Undeclared exception!
      try { 
        w3CDom0.fromJsoup(document0);
        fail("Expecting exception: DOMException");
      
      } catch(DOMException e) {
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Element element0 = mock(Element.class, new ViolatedAssumptionAnswer());
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder((org.w3c.dom.Document) null);
      // Undeclared exception!
      try { 
        w3CDom_W3CBuilder0.tail(element0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.helper.W3CDom$W3CBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Document document0 = mock(Document.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(document0).location();
      doReturn((Element) null).when(document0).child(anyInt());
      org.w3c.dom.Document document1 = w3CDom0.fromJsoup(document0);
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder(document1);
      Node node0 = mock(Node.class, new ViolatedAssumptionAnswer());
      w3CDom_W3CBuilder0.tail(node0, 0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Document document0 = mock(Document.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(document0).location();
      doReturn((Element) null).when(document0).child(anyInt());
      org.w3c.dom.Document document1 = w3CDom0.fromJsoup(document0);
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder(document1);
      Node node0 = mock(Node.class, new ViolatedAssumptionAnswer());
      w3CDom_W3CBuilder0.head(node0, (-1));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Document document0 = mock(Document.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(document0).location();
      doReturn((Element) null).when(document0).child(anyInt());
      org.w3c.dom.Document document1 = w3CDom0.fromJsoup(document0);
      String string0 = w3CDom0.asString(document1);
      assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>", string0);
  }
}
