/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 22:17:48 GMT 2022
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.ParseError;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseError_ESTest extends ParseError_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParseError parseError0 = new ParseError(1162, "s?04", (Object[]) null);
      String string0 = parseError0.toString();
      assertEquals("1162: s?04", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParseError parseError0 = new ParseError(1162, "s?04", (Object[]) null);
      parseError0.getErrorMessage();
      assertEquals(1162, parseError0.getPosition());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParseError parseError0 = new ParseError(1162, "s?04", (Object[]) null);
      int int0 = parseError0.getPosition();
      assertEquals(1162, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseError parseError0 = new ParseError(2476, "");
      assertEquals(2476, parseError0.getPosition());
  }
}
