/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 22:16:29 GMT 2022
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jsoup.nodes.Attributes;
import org.jsoup.parser.ParseSettings;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseSettings_ESTest extends ParseSettings_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(false, false);
      Attributes attributes0 = mock(Attributes.class, new ViolatedAssumptionAnswer());
      doReturn((String) null, (String) null).when(attributes0).toString();
      Attributes attributes1 = parseSettings0.normalizeAttributes(attributes0);
      Attributes attributes2 = parseSettings0.preserveCase.normalizeAttributes(attributes1);
      assertSame(attributes2, attributes0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(false, false);
      String string0 = parseSettings0.preserveCase.normalizeAttribute("org.jsoup.parser.ParseSettings");
      assertEquals("org.jsoup.parser.ParseSettings", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(false, false);
      String string0 = parseSettings0.preserveCase.normalizeTag("org.jsoup.parser.ParseSettings");
      assertEquals("org.jsoup.parser.ParseSettings", string0);
  }
}
